services:
  kv-remote-store:
    image: iotaledger/iota-data-ingestion
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/iota/credentials.json
    volumes:
      - ./config/bigtable.yaml:/iota/config.yaml:r
      # make sure to create the credentials.json file before running this container
      - ./config/credentials.json:/iota/credentials.json:r
      - ./output:/iota/output
    command: >
      iota-data-ingestion
      /iota/config.yaml
