// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package iota.grpc.v0.transactions;

import "common.proto";
import "transaction.proto";

// Transaction subscription service
service TransactionService {
  rpc ExecuteTransaction (ExecuteTransactionRequest) returns (ExecuteTransactionResponse);
  rpc DevInspectTransaction (DevInspectTransactionRequest) returns (DevInspectTransactionResponse);
  rpc DryRunTransaction (DryRunTransactionRequest) returns (DryRunTransactionResponse);
}

// Request to stream transactions with optional filtering
message TransactionStreamRequest {
  TransactionFilter filter = 1;
}

// ExecuteTransaction
message ExecuteTransactionRequest {
  // BCS serialized iota_types::transaction::Transaction
  iota.grpc.v0.common.BcsData transaction = 1;
}

// ExecuteTransactionResponse - Matches REST API
message ExecuteTransactionResponse {
  // BCS-encoded iota_types::effects::TransactionEffects
  // MUST, 
  BcsData effects = 1;

  // Finality information
  // MUST
  iota.grpc.v0.common.EffectsFinality finality = 2;

  // BCS-encoded iota_types::events::TransactionEvents
  // MUST (is it part of the effects?), maybe opt-in
  BcsData events = 3;

  // Balance changes (derived from comparing input/output)
  // To discuss: should we have this for convenience?
  // This is only for wallet users?!
  repeated iota.grpc.v0.common.BalanceChange balance_changes = 4;

  // Full input objects, iota_types::object::Object
  // optional: maybe via flag, or not at all
  repeated BcsData input_objects = 5;

  // Full output objects, iota_types::object::Object
  // optional: maybe via flag, or not at all (objectrefs should be part of the effects)
  repeated BcsData output_objects = 6;
}

// depending on the outcome of an investigation (dry_run vs dev_inspect in the VM executor, and vs simulate_tx)
// defines if we need both API endpoints or not (we should look into upstream, what they use for simulate)

// DevInspectTransaction
message DevInspectTransactionRequest {
  // Sender address
  iota.grpc.v0.common.Address sender = 1;
  // BCS-encoded iota_types::transaction::TransactionKind
  iota.grpc.v0.common.BcsData transaction_kind = 2;
  // Gas price (optional) - gas is not charged but usage is calculated
  optional uint64 gas_price = 3;
  // The epoch to perform the call. Will be set from the system state object if not provided
  optional uint64 epoch = 4;
  // Additional arguments
  optional DevInspectArgs additional_args = 5;
}

message DevInspectArgs {
  // The sponsor of the gas for the transaction
  optional iota.grpc.v0.common.Address gas_sponsor = 1;
  // The gas budget for the transaction.
  optional uint64 gas_budget = 2;
  // The gas objects used to pay for the transaction
  repeated iota.grpc.v0.common.ObjectRef gas_objects = 3;
  // Whether to skip transaction checks for the transaction
  optional bool skip_checks = 4;
  // Whether to return the transaction data
  optional bool show_transaction_data = 5;
}

message DevInspectTransactionResponse {
  // BCS-encoded iota_types::effects::TransactionEffects
  BcsData effects = 1;

  // BCS-encoded iota_types::events::TransactionEvents
  BcsData events = 2;

  // BCS-encoded iota_json_rpc_types::src::IotaExecutionResult
  // To discuss: do we need to redefine this type in grpc types? Do we need this?
  repeated BcsData results = 3;

  // Execution error from executing the transaction
  optional string error = 4;

  // BCS-encoded iota_types::transaction::TransactionData
  optional BcsData transaction_data = 5;
}

// DryRunTransaction
message DryRunTransactionRequest {
  // BCS-encoded iota_types::transaction::TransactionData
  iota.grpc.v0.common.BcsData transaction_data = 1;
}

message DryRunTransactionResponse {
  // BCS-encoded iota_types::effects::TransactionEffects
  BcsData effects = 1;

  // BCS-encoded iota_types::events::TransactionEvents
  optional BcsData events = 2;

  // Object changes
  // To discuss: should we have this for convenience?
  repeated iota.grpc.v0.common.ObjectChange object_changes = 3;

  // Balance changes
  // To discuss: should we have this for convenience?
  repeated iota.grpc.v0.common.BalanceChange balance_changes = 4;

  // BCS-encoded iota_types::transaction::TransactionData
  // To discuss: is this sufficient?
  BcsData transaction_data = 5;

  // Suggested gas price (optional)
  // MUST
  optional uint64 suggested_gas_price = 6;

  // Execution error source (optional, provides detailed error information)
  optional string execution_error_source = 7;
}
