{
 "title": "Cluster Running Status",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "validator", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(latency_s_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{host}} 50%ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(latency_s_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{host}} 95%ile"
    }
   ]
  },
  {
   "title": "Handle Cert 50%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, host) (rate(validator_service_handle_certificate_consensus_latency_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{host}} shared obj txn"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, host) (rate(validator_service_handle_certificate_non_consensus_latency_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{host}} single write txn"
    }
   ]
  },
  {
   "title": "Handle Cert 95%ile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, host) (rate(validator_service_handle_certificate_consensus_latency_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{host}} shared obj txn"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, host) (rate(validator_service_handle_certificate_non_consensus_latency_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{host}} single write txn"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_tx_errors[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Txn Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "rate(quorum_driver_total_ok_responses[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Txn Internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Txn Rate (1m interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "quantile(0.67, sum by (instance) (rate(total_transaction_certificates{instance=~\"$validator\"}[1m])) - sum by (instance) (rate(num_shared_obj_tx{instance=~\"$validator\"}[1m])))",
     "legendFormat": "Owned"
    },
    {
     "expr": "quantile(0.67, rate(num_shared_obj_tx{instance=~\"$validator\"}[1m]))",
     "legendFormat": "Shared"
    }
   ]
  },
  {
   "title": "Txn Manager Executing Cert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum(transaction_manager_num_executing_certificates{instance=~\"$validator\"})",
     "legendFormat": "Sum"
    },
    {
     "expr": "transaction_manager_num_executing_certificates{instance=~\"$validator\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Txn Manager Pending Cert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum(transaction_manager_num_pending_certificates{instance=~\"$validator\"})",
     "legendFormat": "Sum"
    },
    {
     "expr": "transaction_manager_num_pending_certificates{instance=~\"$validator\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Txn Rate (5min interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "quantile(0.67, sum by (instance) (rate(total_transaction_certificates{instance=~\"$validator\"}[5m])) - sum by (instance) (rate(num_shared_obj_tx{instance=~\"$validator\"}[5m])))",
     "legendFormat": "Owned"
    },
    {
     "expr": "quantile(0.67, rate(num_shared_obj_tx{instance=~\"$validator\"}[5m]))",
     "legendFormat": "Shared"
    }
   ]
  },
  {
   "title": "Execution Driver Dispatch Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "execution_driver_dispatch_queue{instance=~\"$validator\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Txn Manager Ready Cert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(transaction_manager_num_ready{instance=~\"$validator\"}[$__rate_interval]))",
     "legendFormat": "Sum"
    },
    {
     "expr": "rate(transaction_manager_num_ready{host=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Try Execute Immediately and Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(authority_state_internal_execution_latency_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(authority_state_commit_certificate_latency_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Manager Tx Enqueue Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "rate(transaction_manager_num_enqueued_certificates{instance=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "{{host}} {{result}}"
    }
   ]
  },
  {
   "title": "Consensus Commit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(consensus_committed_subdags{instance=~\"$validator\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Overload Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "authority_overload_status{instance=~\"$validator\"}",
     "legendFormat": "{{host}} overload status"
    }
   ]
  },
  {
   "title": "Load shedding percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "authority_load_shedding_percentage{instance=~\"$validator\"}",
     "legendFormat": "{{host}} load shedding percentage"
    }
   ]
  },
  {
   "title": "Queueing Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum by(le, instance) (rate(execution_queueing_delay_s_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Shared Object Congestion Control",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "Congested transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(consensus_handler_congested_transactions{instance=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cancelled Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "rate(consensus_handler_cancelled_transactions{instance=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Deferred Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "rate(consensus_handler_deferred_transactions{instance=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Consensus handler max object costs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "consensus_handler_max_object_costs{host=~\"$validator\"}",
     "legendFormat": "{{host}}_{{commit_type}}"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Last Constructed Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(last_constructed_checkpoint{instance=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Checkpoint Age (60%ile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "expr": "histogram_quantile(0.6, sum by(le, host) (rate(last_created_checkpoint_age_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "last_created_checkpoint_age"
    },
    {
     "expr": "histogram_quantile(0.6, sum by(le, host) (rate(last_executed_checkpoint_age_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "last_executed_checkpoint_age"
    },
    {
     "expr": "histogram_quantile(0.6, sum by(le, host) (rate(last_certified_checkpoint_age_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "last_certified_checkpoint_age"
    }
   ]
  },
  {
   "title": "Checkpoint Execution In flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "expr": "checkpoint_exec_inflight{instance=~\"$validator\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Last Executed Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "rate(last_executed_checkpoint{instance=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Checkpoint Age (90%ile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 77 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, host) (rate(last_created_checkpoint_age_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "last_created_checkpoint_age"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, host) (rate(last_executed_checkpoint_age_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "last_executed_checkpoint_age"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, host) (rate(last_certified_checkpoint_age_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "last_certified_checkpoint_age"
    }
   ]
  },
  {
   "title": "Checkpoint Seq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "last_constructed_checkpoint{instance=~\"$validator\"}",
     "legendFormat": "Created {{host}}"
    },
    {
     "expr": "last_executed_checkpoint{instance=~\"$validator\"}",
     "legendFormat": "Executed {{host}}"
    },
    {
     "expr": "last_certified_checkpoint{instance=~\"$validator\"}",
     "legendFormat": "Certified {{host}}"
    },
    {
     "expr": "highest_verified_checkpoint{instance=~\"$validator\"}",
     "legendFormat": "Verified {{host}}"
    }
   ]
  },
  {
   "title": "Checkpoint Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "targets": [
    {
     "expr": "rate(last_constructed_checkpoint{instance=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "Created {{host}}"
    },
    {
     "expr": "rate(last_executed_checkpoint{instance=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "Executed {{host}}"
    },
    {
     "expr": "rate(last_certified_checkpoint{instance=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "Certified {{host}}"
    },
    {
     "expr": "rate(highest_verified_checkpoint{instance=~\"$validator\"}[$__rate_interval])",
     "legendFormat": "Verified {{host}}"
    }
   ]
  },
  { "title": "RocksDb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "RocksDb Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, db_name) (rate(rocksdb_write_batch_commit_latency_seconds_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{db_name}} batch commit"
    }
   ]
  },
  {
   "title": "Get Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 94 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, cf_name) (rate(rocksdb_get_latency_seconds_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Batch Size (KB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 94 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, db_name) (rate(rocksdb_batch_commit_bytes_bucket{instance=~\"$validator\", db_name!=\"checkpoint\"}[$__rate_interval]))) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RocksDb Put Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, cf_name) (rate(rocksdb_put_latency_seconds_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{cf_name}} delete"
    }
   ]
  },
  {
   "title": "Iter Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 102 },
   "targets": [
    {
     "expr": "clamp_max(histogram_quantile(0.95, sum by(le, cf_name) (rate(rocksdb_iter_latency_seconds_bucket{instance=~\"$validator\"}[$__rate_interval]))), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RocksDb Delete Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, cf_name) (rate( rocksdb_delete_latency_seconds_bucket {host=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "{{cf_name}} delete"
    }
   ]
  },
  {
   "title": "Multi Get Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 110 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, cf_name) (rate(rocksdb_multiget_latency_seconds_bucket{instance=~\"$validator\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}