name: TS End-to-end Tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isRpc:
        type: boolean
        required: false
      isExplorer:
        type: boolean
        required: false
      isAppsBackend:
        type: boolean
        required: false
      isTypescriptSDK:
        type: boolean
        required: false
      isWallet:
        type: boolean
        required: false
      isGraphQlTransport:
        type: boolean
        required: false
      isWalletDashboard:
        type: boolean
        required: false
      isEvmBridge:
        type: boolean
        required: false
      isIscSDK:
        type: boolean
        required: false
    secrets:
      EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK:
        required: true
      EVM_BRIDGE_CONFIG:
        required: true

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

env:
  RUST_LOG: warn
  VITE_EVM_BRIDGE_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK }}
  VITE_EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}

jobs:
  # Run e2e test against localnet built on the develop branch
  localnet:
    name: Localnet
    if: inputs.isExplorer || inputs.isTypescriptSDK || inputs.isWallet || inputs.isWalletDashboard || inputs.isEvmBridge || inputs.isRpc || github.ref_name == 'develop'
    runs-on: self-hosted-x64
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespw
          POSTGRES_DB: iota_indexer
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Build Iota binary
        run: cargo build --bin iota --features indexer --profile dev

      - name: Install Nodejs
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Explorer Playwright Browsers
        run: pnpm --filter iota-explorer playwright install --with-deps chromium

      - name: Set environment variables
        run: |
          echo "VITE_IOTA_BIN=$PWD/target/debug/iota" >> $GITHUB_ENV
          echo "E2E_RUN_LOCAL_NET_CMD=(RUST_BACKTRACE=1 $(echo $PWD/target/debug/iota) start --with-faucet --force-regenesis --with-indexer --with-graphql)" >> $GITHUB_ENV

      - name: Run TS SDK e2e tests
        if: (!cancelled()) && (inputs.isTypescriptSDK || inputs.isRpc || github.ref_name == 'develop')
        run: pnpm dlx concurrently --kill-others --success command-1 "$E2E_RUN_LOCAL_NET_CMD" 'pnpm --filter @iota/iota-sdk test:e2e'

      - name: Run RPC/GraphQL compatibility e2e tests
        if: (!cancelled()) && (inputs.isGraphQlTransport || inputs.isRpc || github.ref_name == 'develop')
        run: pnpm dlx concurrently --kill-others --success command-1 "$E2E_RUN_LOCAL_NET_CMD" 'pnpm --filter @iota/graphql-transport test:e2e'

      - name: Build apps-backend
        if: (!cancelled()) && (inputs.isAppsBackend || github.ref_name == 'develop')
        run: pnpm turbo --filter apps-backend build

      - name: Run apps-backend e2e tests
        if: (!cancelled()) && (inputs.isAppsBackend || github.ref_name == 'develop')
        run: pnpm --filter apps-backend test:e2e

      - name: Build explorer
        if: (!cancelled()) && (inputs.isTypescriptSDK || inputs.isExplorer || inputs.isRpc || github.ref_name == 'develop')
        env:
          IOTA_NETWORKS: '{ "localnet": { "id": "localnet", "name": "Localnet", "url": "http://localhost:9124", "explorer": "http://localhost:3000", "chain": "iota:local", "faucet": "http://localhost:9123" } }'
        run: pnpm turbo --filter=iota-explorer build

      - name: Run Explorer e2e tests
        if: (!cancelled()) && (inputs.isTypescriptSDK || inputs.isExplorer || inputs.isRpc || github.ref_name == 'develop')
        run: pnpm --filter iota-explorer playwright test

      - name: Upload Explorer test reports
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: (!cancelled())
        with:
          name: playwright-report-explorer
          path: apps/explorer/playwright-report/
          retention-days: 30

      - name: Build Wallet
        if: (!cancelled()) && (inputs.isWalletDashboard || inputs.isWallet || inputs.isRpc || inputs.isTypescriptSDK || github.ref_name == 'develop')
        run: pnpm wallet build

      - name: Build Dashboard
        if: (!cancelled()) && (inputs.isWalletDashboard || inputs.isRpc || inputs.isTypescriptSDK || github.ref_name == 'develop')
        run: pnpm turbo --filter wallet-dashboard build

      - name: Run Dashboard e2e tests
        if: (!cancelled()) && (inputs.isWalletDashboard || inputs.isRpc || inputs.isTypescriptSDK || github.ref_name == 'develop')
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm --filter wallet-dashboard playwright test

      - name: Upload Dashboard test reports
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: (!cancelled())
        with:
          name: playwright-report-wallet-dashboard
          path: apps/wallet-dashboard/playwright-report/
          retention-days: 30

      - name: Build Kiosk
        if: (!cancelled()) && (inputs.isRpc || inputs.isTypescriptSDK || github.ref_name == 'develop')
        run: pnpm turbo --filter=@iota/kiosk build

      - name: Run Kiosk e2e tests
        if: (!cancelled()) && (inputs.isRpc || inputs.isTypescriptSDK || github.ref_name == 'develop')
        run: pnpm dlx concurrently --kill-others --success command-1 "$E2E_RUN_LOCAL_NET_CMD" 'pnpm --filter=@iota/kiosk test:e2e'

      - name: Run Local net
        if: (!cancelled())
        run: cargo run --bin iota start --force-regenesis --with-faucet --epoch-duration-ms 10000 &

      - name: Run Wallet e2e tests
        if: (!cancelled()) && (inputs.isWallet || inputs.isRpc || inputs.isTypescriptSDK || github.ref_name == 'develop')
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm --filter iota-wallet playwright test

      - name: Upload Wallet test reports
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: (!cancelled())
        with:
          name: playwright-report-wallet
          path: apps/wallet/playwright-report/
          retention-days: 30

      - name: Build Evm-bridge
        if: (!cancelled()) && (inputs.isEvmBridge || inputs.isIscSDK || inputs.isTypescriptSDK || github.ref_name == 'develop')
        run: pnpm evm-bridge build

      - name: Install Playwright Browsers for Evm-bridge
        if: (!cancelled()) && (inputs.isEvmBridge || inputs.isIscSDK || inputs.isTypescriptSDK || github.ref_name == 'develop')
        run: pnpm --filter ./apps/evm-bridge playwright install --with-deps chromium

      - name: Prepare evm-bridge e2e tests (downloads wallet artifact dist)
        if: (!cancelled()) && (inputs.isEvmBridge || inputs.isIscSDK || inputs.isTypescriptSDK || github.ref_name == 'develop')
        working-directory: ./apps/evm-bridge
        run: pnpm run test:prepare

      - name: Run evm-bridge tests
        if: (!cancelled()) && (inputs.isEvmBridge || inputs.isIscSDK || inputs.isTypescriptSDK || github.ref_name == 'develop')
        working-directory: ./apps/evm-bridge
        run: DEBUG=pw:webserver xvfb-run --auto-servernum pnpm run test:e2e

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: (!cancelled())
        with:
          name: playwright-report-evm-bridge
          path: apps/evm-bridge/playwright-report/
          retention-days: 30
