name: Ledgernano End-to-end Tests

on: workflow_call

concurrency:
  group: ledgernano-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

jobs:
  ledgernano:
    name: Ledgernano
    runs-on: self-hosted-x64
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Nodejs
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Pull speculos docker image
        run: docker pull ghcr.io/ledgerhq/speculos

      - name: Download ledgernano binary
        run: |
          curl -L -o nanos.tar.gz https://github.com/iotaledger/ledger-app-iota/releases/download/ledger-app-iota-v0.9.2/nanos.tar.gz
          tar -xvf nanos.tar.gz
          mv nanos/iota sdk/ledgerjs-hw-app-iota/tests/iota

      - name: Start speculos simulator
        run: docker run --rm -d -p 5000:5000 -v $(pwd)/sdk/ledgerjs-hw-app-iota/tests:/app ghcr.io/ledgerhq/speculos --api-port 5000 --display headless /app/iota

      - name: Run TS SDK ledgernano tests
        run: pnpm --filter @iota/ledgerjs-hw-app-iota test
