name: Production Deploy for the IOTA EVM Bridge

on: workflow_dispatch

env:
  VERCEL_PROJECT_ID: ${{ secrets.EVM_BRIDGE_VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VITE_EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}
  VITE_EVM_BRIDGE_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PROD_DEFAULT_NETWORK }}

jobs:
  vercel-deploy:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    runs-on: [self-hosted-x64]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4.0.0

      - name: Install Nodejs
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Vercel CLI
        run: pnpm add --global vercel@canary

      - name: Install Project Dependencies
        run: pnpm install --frozen-lockfile

      - name: Pull Vercel Environment Information
        run: vercel pull --token=${{ secrets.VERCEL_TOKEN }} --yes --environment=production

      - name: Build Project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --target=production

      - name: Deploy to Vercel Action
        uses: iotaledger/deploy-to-vercel-action@9c73fe8ff3eb32d6ba30d623ac1b0c5708a25bb7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.EVM_BRIDGE_VERCEL_PROJECT_ID }}
          PREBUILT: true
          DELETE_EXISTING_COMMENT: false
          VERCEL_TARGET: production
