name: Turborepo Nightly checks

on:
  schedule:
    - cron: "0 21 * * *" # daily at 9:00 PM (UTC)
  workflow_dispatch:

jobs:
  e2e:
    uses: ./.github/workflows/_e2e.yml
    secrets:
      EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK: ${{ secrets.EVM_BRIDGE_PREVIEW_DEFAULT_NETWORK }}
      EVM_BRIDGE_CONFIG: ${{ secrets.EVM_BRIDGE_CONFIG }}
  check-sri-integrity-webassets:
    uses: ./.github/workflows/check_sri.yml
