// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package iota.grpc.v0.filters;

import "common.proto";

// Logical AND of several filters.
message AllEventFilter {
  repeated EventFilter filters = 1;
}

// Logical OR of several filters.
message AnyEventFilter {
  repeated EventFilter filters = 1;
}

// Logical NOT of a filter.
message NotEventFilter {
  EventFilter filter = 1;
}

// Filter by address.
message AddressFilter {
  iota.grpc.v0.common.Address address = 1;
}

// Filter by Move package + module (optional).
message MovePackageAndModuleFilter {
  iota.grpc.v0.common.Address package_id = 1;
  optional string module = 2;
}

// Filter by the given Move event struct name (struct tag).
// For example, if the event is defined in `0xabcd::MyModule`, and named
// `Foo`, then the struct tag is `0xabcd::MyModule::Foo`.
message MoveEventTypeFilter {
  string struct_tag = 1;
}

// Filter by Move event field (JSON pointer as defined in RFC 6901 + value (optional)).
message MoveEventFieldFilter {
  string json_pointer = 1;
  optional string value = 2;
}

// Filter for events.
message EventFilter {
  oneof filter {
    // Logical AND of several filters.
    AllEventFilter all = 1;
    // Logical OR of several filters.
    AnyEventFilter any = 2;
    // Logical NOT of a filter.
    NotEventFilter not = 3;

    // Filter by sender address.
    AddressFilter sender = 4;

    // Return events emitted in a specified Move package + module (optional).
    // If the event is defined in PackageA::ModuleA but emitted in a tx with PackageB::ModuleB,
    // filtering `MovePackageAndModule` by PackageB::ModuleB returns the event.
    // Filtering `MoveEventPackageAndModule` by PackageA::ModuleA returns the event too.
    MovePackageAndModuleFilter move_package_and_module = 5;
    // Return events with the given Move package + module (optional) where the event struct is
    // defined. If the event is defined in PackageA::ModuleA but emitted in a tx
    // with PackageB::ModuleB, filtering `MoveEventPackageAndModule` by PackageA::ModuleA returns the
    // event. Filtering `MovePackageAndModule` by PackageB::ModuleB returns the event too.
    MovePackageAndModuleFilter move_event_package_and_module = 6;
    // Return events with the given Move event struct name (struct tag).
    // For example, if the event is defined in `0xabcd::MyModule`, and named
    // `Foo`, then the struct tag is `0xabcd::MyModule::Foo`.
    MoveEventTypeFilter move_event_type = 7;
    // Return events whose JSON representation contains the given field path
    // with the specified value (optional). The path should be a JSON pointer as
    // defined in RFC 6901.
    MoveEventFieldFilter move_event_field = 8;
  }
}

// Logical AND of several filters.
message AllTransactionFilter {
  repeated TransactionFilter filters = 1;
}

// Logical OR of several filters.
message AnyTransactionFilter {
  repeated TransactionFilter filters = 1;
}

// Logical NOT of a filter.
message NotTransactionFilter {
  TransactionFilter filter = 1;
}

// Filter by transaction kinds (any of the specified kinds).
message TransactionKindsFilter {
  repeated iota.grpc.v0.common.TransactionKind kinds = 1;
}

// Filter by input object ID.
message ObjectIdFilter {
  iota.grpc.v0.common.Address object_id = 1;
}

// Filter by move package, module (optional) and function (optional).
message MoveCallFilter {
  iota.grpc.v0.common.Address package_id = 1;
  optional string module = 2;
  optional string function = 3;
}

// Filter for transactions.
message TransactionFilter {
  oneof filter {
    // Logical AND of several filters.
    AllTransactionFilter all = 1;
    // Logical OR of several filters.
    AnyTransactionFilter any = 2;
    // Logical NOT of a filter.
    NotTransactionFilter not = 3;

    // Filter transactions of any given kind in the filter.
    TransactionKindsFilter transaction_kinds = 4;

    // Filter by sender address.
    AddressFilter sender = 5;
    // Filter by recipient address. The recipient is determined by
    // checking the owners of mutated and unwrapped objects.
    AddressFilter receiver = 6;

    // Filter by input object.
    ObjectIdFilter input_object = 7;
    // Filter by changed object, including created, mutated and unwrapped
    // objects.
    ObjectIdFilter changed_object = 8;
    // Filter transactions that wrapped or deleted the specified object.
    // Includes transactions that either created and immediately wrapped
    // the object or unwrapped and immediately deleted it.
    ObjectIdFilter wrapped_or_deleted_object = 9;
    // Filter for transactions that touch this object.
    ObjectIdFilter affected_object = 10;

    // Filter by move package, module (optional) and function (optional).
    MoveCallFilter move_call = 11;

    // Filter transactions that contain events matching the given event filter.
    EventFilter event = 12;
  }
}
