// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package iota.grpc.v0.signature;

import "iota/grpc/v0/common.proto";

// A signature from a user.
message UserSignature {
  // This signature serialized as as BCS.
  //
  // When provided as input this will support both the form that is length
  // prefixed as well as not length prefixed.
  optional BcsData bcs = 1;
}

// A list of user signatures.
message UserSignatures {
  repeated UserSignature signatures = 1;
}

/// An aggregated signature from multiple validators.
message ValidatorAggregatedSignature {
  optional BcsData bcs = 1;
}
