// Copyright (c) Mysten Labs, Inc.
// Modifications Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package iota.grpc.v0.transaction;

import "google/protobuf/timestamp.proto";
import "iota/grpc/v0/common.proto";
import "iota/grpc/v0/object.proto";
import "iota/grpc/v0/signature.proto";
import "iota/grpc/v0/event.proto";

// A transaction.
message Transaction {
  // This Transaction serialized as BCS.
  optional BcsData bcs = 1;

  // The digest of this Transaction.
  optional string digest = 2;
}

// The effects of executing a transaction.
message TransactionEffects {
  // This TransactionEffects serialized as BCS.
  optional BcsData bcs = 1;

  // The digest of this TransactionEffects.
  optional Digest digest = 2;
}

// Events emitted during the successful execution of a transaction.
message TransactionEvents {
  // This TransactionEvents serialized as BCS.
  optional BcsData bcs = 1;

  // The digest of this TransactionEvents.
  optional string digest = 2;

  // List of events emitted by a transaction.
  optional Events events = 3;
}

// A transaction that has been executed, along with its signatures, effects, events and objects.
message ExecutedTransaction {
  // The digest of this Transaction.
  optional string digest = 1;

  // The transaction itself.
  optional Transaction transaction = 2;

  // List of user signatures that are used to authorize the
  // execution of this transaction.
  optional UserSignatures signatures = 3;

  // The `TransactionEffects` for this transaction.
  optional TransactionEffects effects = 4;

  // The `TransactionEvents` for this transaction.
  //
  // This field might be empty, even if it was explicitly requested, if the
  // transaction didn't produce any events.
  // `iota.types.TransactionEffects.events_digest` is populated if the
  // transaction produced any events.
  optional TransactionEvents events = 5;

  // The sequence number for the checkpoint that includes this transaction.
  optional uint64 checkpoint = 6;

  // The Unix timestamp of the checkpoint that includes this transaction.
  optional google.protobuf.Timestamp timestamp = 7;

  // Set of input objects used by this transaction.
  optional Objects input_objects = 9;

  // Set of output objects produced by this transaction.
  optional Objects output_objects = 10;
}

message ExecutedTransactions {
  repeated ExecutedTransaction transactions = 1;
}