// Copyright (c) 2025 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

syntax = "proto3";

package iota.grpc.v0.write;

import "common.proto";

service WriteService {
  rpc ExecuteTransaction (ExecuteTransactionRequest) returns (ExecuteTransactionResponse);
  rpc DevInspectTransaction (DevInspectTransactionRequest) returns (DevInspectTransactionResponse);
  rpc DryRunTransaction (DryRunTransactionRequest) returns (DryRunTransactionResponse);
}

// ExecuteTransaction
message ExecuteTransactionRequest {
  // BCS serialized iota_types::transaction::Transaction
  iota.grpc.v0.common.BcsData transaction = 1;
}

// ExecuteTransactionResponse - Matches REST API
message ExecuteTransactionResponse {
  // BCS-encoded iota_types::effects::TransactionEffects
  iota.grpc.v0.common.Bcs effects = 1;

  // Finality information
  iota.grpc.v0.common.EffectsFinality finality = 2;

  // BCS-encoded iota_types::events::TransactionEvents
  iota.grpc.v0.common.Bcs events = 3;

  // Balance changes (derived from comparing input/output)
  // To discuss: should we have this for convenience?
  repeated iota.grpc.v0.common.BalanceChange balance_changes = 4;

  // Full input objects, iota_types::object::Object
  repeated iota.grpc.v0.common.Bcs input_objects = 5;

  // Full output objects, iota_types::object::Object
  repeated iota.grpc.v0.common.Bcs output_objects = 6;
}

// DevInspectTransaction
message DevInspectTransactionRequest {
  // Sender address
  iota.grpc.v0.common.Address sender = 1;
  // BCS-encoded iota_types::transaction::TransactionKind
  iota.grpc.v0.common.BcsData transaction_kind = 2;
  // Gas price (optional) - gas is not charged but usage is calculated
  optional uint64 gas_price = 3;
  // The epoch to perform the call. Will be set from the system state object if not provided
  optional uint64 epoch = 4;
  // Additional arguments
  optional DevInspectArgs additional_args = 5;
}

message DevInspectArgs {
  // The sponsor of the gas for the transaction
  optional iota.grpc.v0.common.Address gas_sponsor = 1;
  // The gas budget for the transaction.
  optional uint64 gas_budget = 2;
  // The gas objects used to pay for the transaction
  repeated iota.grpc.v0.common.ObjectRef gas_objects = 3;
  // Whether to skip transaction checks for the transaction
  optional bool skip_checks = 4;
  // Whether to return the transaction data
  optional bool show_transaction_data = 5;
}

message DevInspectTransactionResponse {
  // BCS-encoded iota_types::effects::TransactionEffects
  iota.grpc.v0.common.Bcs effects = 1;

  // BCS-encoded iota_types::events::TransactionEvents
  iota.grpc.v0.common.Bcs events = 2;

  // BCS-encoded iota_json_rpc_types::src::IotaExecutionResult
  // To discuss: do we need to redefine this type in grpc types? Do we need this?
  repeated iota.grpc.v0.common.Bcs results = 3;

  // Execution error from executing the transaction
  optional string error = 4;

  // BCS-encoded iota_types::transaction::TransactionData
  optional iota.grpc.v0.common.Bcs transaction_data = 5;
}

// DryRunTransaction
message DryRunTransactionRequest {
  // BCS-encoded iota_types::transaction::TransactionData
  iota.grpc.v0.common.BcsData transaction_data = 1;
}

message DryRunTransactionResponse {
  // BCS-encoded iota_types::effects::TransactionEffects
  iota.grpc.v0.common.Bcs effects = 1;

  // BCS-encoded iota_types::events::TransactionEvents
  optional iota.grpc.v0.common.Bcs events = 2;

  // Object changes
  // To discuss: should we have this for convenience?
  repeated iota.grpc.v0.common.ObjectChange object_changes = 3;

  // Balance changes
  // To discuss: should we have this for convenience?
  repeated iota.grpc.v0.common.BalanceChange balance_changes = 4;

  // BCS-encoded iota_types::transaction::TransactionData
  // To discuss: is this sufficient?
  iota.grpc.v0.common.Bcs transaction_data = 5;

  // Suggested gas price (optional)
  optional uint64 suggested_gas_price = 6;

  // Execution error source (optional, provides detailed error information)
  // Presented in https://github.com/MystenLabs/sui/issues/21375
  optional string execution_error_source = 7;
}
